### ISSUE TITLE
Add License and a .gitattributes file

### ISSUE THREAD

**Issue by CyberCitizen01** [ERC-IIITH/MATLAB-Library#3]
I would really suggest adding a `CC BY-NC-SA` [^1] License to the library and a .gitattributes file to normalize line endings. Also it would be a little addition to the repo's ecosystem to have a word regarding. all files to be ending with a newline or better maybe also add an action [^2] to check (and fix) files to end with a newline (As it is considered as a good practice for files to end with a newline).

I would be more than happy to add the above mentioned License and .gitattributes files to the repo. And for the rest part of suggestion, I will leave it your organization's decision.

[^1]: For more information on what exactly this means, see https://creativecommons.org/licenses/by-nc-sa/4.0/
[^2]: I have found two such actions, [linelint](https://github.com/marketplace/actions/linelint#GitHub-Actions) and [newline-action](https://github.com/marketplace/actions/newline-action)

**Comment by CyberCitizen01** [comment]
I went ahead and created an issue in each repository, so that people visiting them would know, a discussion about this is going on in this thread.
(I'm justifying myself so that, this is not considered as spam but rather an intention to make things better for the community)

**Comment by adithyasunil26** [comment]
@CyberCitizen01 Yes a licence is needed. We started this project a day ago so that's something we did not think of yet. Can you elaborate on why you are suggesting an NC license over something that offers more freedom like the MIT license? 

Yes, the line endings are something that just came to our attention as well. If you would like to add the `.gitattributes` please go ahead.

**Comment by CyberCitizen01** [comment]
@adithyasunil26 Sorry for the late reply, I have been busy lately..

Well it comes to your organization's perspective about the goal and outcome of the project.
I simply suggested `CC BY-NC-SA` license, thinking that since it restricts from using the project for commercial purposes, someone would not just make a copy of the repo and sell it as a book. But yeah if you think MIT license would best suit the project's goals then its great, and I will be happy to include it in a PR 🎉 

> Yes, the line endings are something that just came to our attention as well. If you would like to add the .gitattributes please go ahead.

Thanks !! 
but I should add it in all the 4 repos ryt? and it would be nice of you, if you can assign the issues to me.

**Comment by adithyasunil26** [comment]
@CyberCitizen01 It's alright.

I think we can proceed with an MIT licence for now.

Sure, I will assign you the issues. Thanks.

**Comment by CyberCitizen01** [comment]
@adithyasunil26 Great 🌻 
(Will try to do it by evening.)
